#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Fixtures for K2-Horizon's eager decode attention (B70_K2_ATTN=eager; spec 18 §10).

Runs k2_ref.py's `attention()` - transformers' bf16 eager path, bit-identical to the vendored
modeling_k2_horizon.py (test_k2_ref.py) - on deterministic inputs and writes its scores, its
probabilities and its output as a C++ header, which tests/kernels/k2_attn_eager_ref_test.cc
holds tests/kernels/k2_ref.h's eager chain to, bit for bit.

    tools/oracle/k2_attn_eager_fixture.py > tests/kernels/k2_attn_eager_fixture.h

Run it in the oracle container (the Mac has docker; no checkpoint, seconds, < 1 GB):

    docker run --rm --memory 28g -v "$PWD:/ws" -w /ws --entrypoint python3 agnes-ref-img:latest \\
      tools/oracle/k2_attn_eager_fixture.py > tests/kernels/k2_attn_eager_fixture.h

The inputs are not stored: both sides draw them from the same integer hash (lowbias32, `val()`
below and `k2_ref::eager_fixture_val` in C++), so the header carries only what torch computed.
Three cases:

  coarse   q in steps of 1/2, k and v in steps of 1/8: every q·k product and partial sum is
           exact in fp32 (|sum| <= 512 at a 2^-4 grain, 14 bits), so the score is the same in
           ANY accumulation order and torch's GEMM order cannot show through - the scores are
           a bitwise check of the rounding points alone. 3 query rows (a prompt pass: the
           causal mask, rows padded with -inf to P).
  decode   one row over 300 keys, generic bf16 values (q·k inexact: torch's GEMM order and
           ours may round apart, which the test counts and bounds rather than hides).
  prompt   4 rows over 40 keys, generic values.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or os.getcwd()) != _HERE]

import importlib.util  # noqa: E402

import torch  # noqa: E402

_spec = importlib.util.spec_from_file_location("k2_ref", os.path.join(_HERE, "k2_ref.py"))
ref = importlib.util.module_from_spec(_spec)
sys.modules["k2_ref"] = ref
_spec.loader.exec_module(ref)

HEADS, KV_HEADS, HD = 8, 2, 128      # K2's GQA 4 and head_dim, at two kv heads
M32 = 0xFFFFFFFF


def lowbias32(x: int) -> int:
    x &= M32
    x ^= x >> 16
    x = (x * 0x7FEB352D) & M32
    x ^= x >> 15
    x = (x * 0x846CA68B) & M32
    x ^= x >> 16
    return x


def val(kind: str, tensor: int, i: int, seed: int) -> float:
    """The input generator (k2_ref::eager_fixture_val is its C++ twin): element i of tensor
    0 (q), 1 (k) or 2 (v). `coarse`: (h % 17 - 8) x step, step 1/2 for q, 1/8 for k and v.
    `fine`: ((h >> 8) x 2^-23 - 1) x amp (exact in fp32), amp 4 for q, 1 for k and v, then
    rounded to bf16 (RNE, torch's .to(bfloat16))."""
    h = lowbias32(lowbias32(seed * 3 + tensor) ^ i)
    if kind == "coarse":
        return float((h % 17) - 8) * (0.5 if tensor == 0 else 0.125)
    amp = 4.0 if tensor == 0 else 1.0
    f = torch.tensor([(h >> 8) * 2.0 ** -23 - 1.0], dtype=torch.float32) * amp
    return float(f.to(torch.bfloat16).float()[0])


def tensor(kind, t, shape, seed):
    n = 1
    for s in shape:
        n *= s
    return torch.tensor([val(kind, t, i, seed) for i in range(n)], dtype=torch.float32).reshape(shape)


def bits(x: torch.Tensor) -> list:
    return x.contiguous().to(torch.bfloat16).view(torch.int16).flatten().tolist()


def hexs(name: str, xs: list) -> str:
    h = "".join(f"{v & 0xFFFF:04x}" for v in xs)
    lines = [f'    "{h[i:i + 128]}"' for i in range(0, len(h), 128)]
    return f"inline constexpr char {name}[] =\n" + "\n".join(lines) + ";\n"


CASES = [  # name, kind, seed, T (rows), P (keys); rows are the LAST T positions
    ("coarse", "coarse", 1, 3, 77),
    ("decode", "fine", 2, 1, 300),
    ("prompt", "fine", 3, 4, 40),
]


def main() -> None:
    ar = ref.Arith("bf16")
    n_rep = HEADS // KV_HEADS
    out = [
        "#pragma once",
        "// GENERATED by tools/oracle/k2_attn_eager_fixture.py in agnes-ref-img:latest "
        f"(torch {torch.__version__}, CPU capability {torch.backends.cpu.get_cpu_capability()}) - do not edit.",
        "// k2_ref.py attention() (transformers' bf16 eager path) on the hash inputs of",
        "// k2_ref::eager_fixture_val: scores s and probabilities p bf16 [heads][T][P] (masked entries",
        "// -inf / 0), output o bf16 [T][heads][128]. 4 hex digits per bf16 value.",
        "namespace k2_attn_eager_fixture {",
        f"inline constexpr unsigned kHeads = {HEADS}, kKvHeads = {KV_HEADS}, kHd = {HD};",
    ]
    for name, kind, seed, T, P in CASES:
        q = tensor(kind, 0, (HEADS, T, HD), seed)
        k = tensor(kind, 1, (KV_HEADS, P, HD), seed)
        v = tensor(kind, 2, (KV_HEADS, P, HD), seed)
        q_pos = torch.arange(P - T, P)
        k_pos = torch.arange(P)
        o = ref.attention(ar, q, k, v, q_pos, k_pos, n_rep)            # [T, H, d]
        # attention()'s own lines, for the intermediates (and held to its output below).
        kk = k.repeat_interleave(n_rep, dim=0)
        vv = v.repeat_interleave(n_rep, dim=0)
        s = ar.r(ar.mm(q, kk.transpose(1, 2)) * (HD ** -0.5))
        s = s.masked_fill((k_pos[None, :] > q_pos[:, None])[None], float("-inf"))
        p = ar.r(torch.softmax(s, dim=-1))
        assert torch.equal(ar.mm(p, vv).transpose(0, 1), o), name
        out.append(f"// {name}: {kind} inputs, seed {seed}, {T} row(s) at positions {P - T}..{P - 1}, {P} keys")
        out.append(f'inline constexpr const char* k{name.capitalize()}Kind = "{kind}";')
        out.append(f"inline constexpr unsigned k{name.capitalize()}Seed = {seed}, "
                   f"k{name.capitalize()}T = {T}, k{name.capitalize()}P = {P};")
        out.append(hexs(f"k{name.capitalize()}S", bits(s)))
        out.append(hexs(f"k{name.capitalize()}Pr", bits(p)))
        out.append(hexs(f"k{name.capitalize()}O", bits(o)))
    out.append("}  // namespace k2_attn_eager_fixture")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
