#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""The Kolibri-1 kernel-chain fixture (spec 20c Task 1 Step 5): tools/oracle/kolibri_ref.py's OWN
functions run in bf16 mode on deterministic inputs at the real widths, their outputs written as a C++
header that tests/kernels/kolibri_ref_test.cc holds tests/kernels/kolibri_ref.h to.

    tools/oracle/kolibri_fixture.py > tests/kernels/kolibri_fixture.h

Run it in the oracle container (seconds, < 1 GB, no checkpoint):

    docker run --rm --memory 8g --cpus 2 -v "$PWD:/ws" -w /ws --entrypoint python3 agnes-ref-img:latest \\
      tools/oracle/kolibri_fixture.py > tests/kernels/kolibri_fixture.h

Inputs are not stored where a hash can make them: both sides draw them from the same integer hash
(lowbias32: `val()` below, `kolibri_ref::fixture_val` in C++). `coarse` values are small multiples of a
power of two, so every dot and sum of squares below is exact in fp32 in ANY order and the comparison
is a bitwise check of the rounding points alone; `fine` values are generic bf16. The cases:

  (a) rms_norm      one hidden row (2560): coarse x with w = 1, 0, 2 and a random bf16 w; a fine x
                    with the random w (its Σx² is order-dependent: the test bounds it)
  (b) q/k norm      one q head and one k head (128) through rms_norm with q_norm / k_norm, then (sliding
                    layers) RoPE (rope_cos_sin + rotate_half) at positions 0, 1, 513, 100000, 262143; the
                    normed heads alone are the full layers' (NoPE); the cos / sin rows themselves
  (c) route         4 rows of 384 fp32 logits + a bias: random; a tie at the cut (ranks 6 / 7 equal: the
                    lower id goes); a bias that reorders the top 6; every logit -1e30 with zero bias
  (d) combine       moe()'s ascending-id fp32 combine of 6 expert rows + the shared row, one rounding
  (e) attention     eager attention(), 12 q heads on one kv head (GQA 12), coarse inputs, key p's
                    elements drawn at index p x 128 + d (absolute positions): sliding at query 5 (the
                    prompt pass's row: 8 keys, 6 visible), 512 (keys 0..512), 513 (1..513), 700
                    (188..700) - the cached decode pass's rows - and full at 700 (0..700). Scores and
                    probabilities of head 0, the output of every head.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or os.getcwd()) != _HERE]

import importlib.util  # noqa: E402

import torch  # noqa: E402

_spec = importlib.util.spec_from_file_location("kolibri_ref", os.path.join(_HERE, "kolibri_ref.py"))
ref = importlib.util.module_from_spec(_spec)
sys.modules["kolibri_ref"] = ref
_spec.loader.exec_module(ref)

M32 = 0xFFFFFFFF
D, HD, E, TOPK = 2560, 128, 384, 6
EPS = 1e-6
ROPE_POS = [0, 1, 513, 100000, 262143]
ATTN_CASES = [  # name, sliding, query position, keys [lo, hi], row length (keys >= the query masked)
    ("s5", True, 5, 0, 7),
    ("s512", True, 512, 0, 512),
    ("s513", True, 513, 1, 513),
    ("s700", True, 700, 188, 700),
    ("f700", False, 700, 0, 700),
]
ATTN_HEADS = 12


def lowbias32(x: int) -> int:
    x &= M32
    x ^= x >> 16
    x = (x * 0x7FEB352D) & M32
    x ^= x >> 15
    x = (x * 0x846CA68B) & M32
    x ^= x >> 16
    return x


def val(coarse: bool, t: int, i: int, seed: int, step: float = 0.125, amp: float = 1.0) -> float:
    """kolibri_ref::fixture_val's twin: element i of input tensor t. coarse: (h % 17 - 8) x step.
    fine: ((h >> 8) x 2^-23 - 1) x amp (exact in fp32), rounded to bf16."""
    h = lowbias32(lowbias32(seed * 3 + t) ^ i)
    if coarse:
        return float((h % 17) - 8) * step
    f = torch.tensor([(h >> 8) * 2.0 ** -23 - 1.0], dtype=torch.float32) * amp
    return float(f.to(torch.bfloat16).float()[0])


def vec(coarse, t, n, seed, step=0.125, amp=1.0, base=0):
    return torch.tensor([val(coarse, t, base + i, seed, step, amp) for i in range(n)], dtype=torch.float32)


def bits16(x: torch.Tensor) -> list:
    return (x.contiguous().to(torch.bfloat16).view(torch.int16).flatten().int() & 0xFFFF).tolist()


def bits32(x: torch.Tensor) -> list:
    return (x.contiguous().float().view(torch.int32).flatten().long() & M32).tolist()


def hexs(name: str, xs: list, width: int) -> str:
    h = "".join(f"{v:0{width}x}" for v in xs)
    lines = [f'    "{h[i:i + 128]}"' for i in range(0, len(h), 128)]
    return f"inline constexpr char {name}[] =\n" + "\n".join(lines) + ";\n"


def main() -> None:
    ops = ref.Ops("bf16")
    out = [
        "#pragma once",
        "// GENERATED by tools/oracle/kolibri_fixture.py in agnes-ref-img:latest "
        f"(torch {torch.__version__}, CPU capability {torch.backends.cpu.get_cpu_capability()}) - do not edit.",
        "// tools/oracle/kolibri_ref.py's own functions (bf16 mode) on kolibri_ref::fixture_val's inputs;",
        "// 4 hex digits per bf16 value, 8 per fp32 / u32. The script's docstring has the cases.",
        "namespace kolibri_fixture {",
        f"inline constexpr unsigned kHidden = {D}, kHd = {HD}, kExperts = {E}, kTopK = {TOPK};",
    ]

    # (a) rms_norm over one hidden row
    xc = vec(True, 0, D, 1, step=0.125)
    xf = vec(False, 0, D, 2, amp=4.0)
    wr = (1.0 + vec(False, 1, D, 1, amp=0.5)).to(torch.bfloat16).float()
    ws = {"One": torch.ones(D), "Zero": torch.zeros(D), "Two": torch.full((D,), 2.0), "Rand": wr}
    out.append("// (a) rms_norm: x coarse (t 0, seed 1, step 1/8) with w = 1, 0, 2, random; x fine (t 0, seed 2,")
    out.append("//     amp 4) with the random w (t 1, seed 1: rf(1 + fine x 0.5))")
    for k, w in ws.items():
        y = ref.rms_norm(ops, xc.to(torch.bfloat16)[None], w.to(torch.bfloat16), EPS)[0]
        out.append(hexs(f"kNormCoarse{k}", bits16(y), 4))
    out.append(hexs("kNormFineRand", bits16(ref.rms_norm(ops, xf.to(torch.bfloat16)[None], wr.to(torch.bfloat16), EPS)[0]), 4))

    # (b) q / k norm + RoPE
    qx = vec(True, 2, HD, 3, step=0.25)
    kx = vec(True, 3, HD, 3, step=0.25)
    qw = (1.0 + vec(False, 4, HD, 3, amp=0.5)).to(torch.bfloat16)
    kw = (1.0 + vec(False, 5, HD, 3, amp=0.5)).to(torch.bfloat16)
    qn = ref.rms_norm(ops, qx.to(torch.bfloat16)[None], qw, EPS)[0]
    kn = ref.rms_norm(ops, kx.to(torch.bfloat16)[None], kw, EPS)[0]
    pos = torch.tensor(ROPE_POS)
    cos, sin = ref.rope_cos_sin(ops, pos, HD, 1e4)                       # [P, 128] bf16
    qr = (qn[None] * cos) + (ref.rotate_half(qn[None]) * sin)            # [P, 128], the reference's lines
    kr = (kn[None] * cos) + (ref.rotate_half(kn[None]) * sin)
    out.append("// (b) q head x (t 2, seed 3, coarse step 1/4), k head (t 3), q_norm / k_norm w (t 4 / 5: rf(1 + fine x 0.5));")
    out.append("//     normed heads (the full layers' q / k), then RoPE'd at kRopePos; cos / sin rows [P][64]")
    out.append(f"inline constexpr unsigned kRopeN = {len(ROPE_POS)};")
    out.append("inline constexpr unsigned kRopePos[] = {" + ", ".join(map(str, ROPE_POS)) + "};")
    out.append(hexs("kQNormed", bits16(qn), 4))
    out.append(hexs("kKNormed", bits16(kn), 4))
    out.append(hexs("kQRoped", bits16(qr), 4))
    out.append(hexs("kKRoped", bits16(kr), 4))
    out.append(hexs("kRopeCos", bits16(cos[:, :HD // 2]), 4))
    out.append(hexs("kRopeSin", bits16(sin[:, :HD // 2]), 4))

    # (c) route
    g = torch.Generator().manual_seed(20)
    logits = torch.zeros(4, E)
    bias = torch.zeros(4, E)
    logits[0] = torch.randn(E, generator=g) * 2.0
    bias[0] = (torch.randn(E, generator=g) * 0.5).to(torch.bfloat16).float()
    # row 1: a tie at the cut - five experts clearly ahead, experts 77 and 300 tied for the sixth place
    logits[1] = -4.0 + 0.125 * torch.randint(-8, 8, (E,), generator=g).float()
    bias[1] = 0.0
    for e in (5, 50, 100, 150, 200):
        logits[1, e] = 2.0
    logits[1, 77] = 1.0
    bias[1, 300] = 0.5
    logits[1, 300] = 0.5
    # row 2: the bias reorders - by logit the top six are 10..15, the bias lifts 20..25 above them
    logits[2] = -3.0 + 0.0625 * torch.randint(-8, 8, (E,), generator=g).float()
    logits[2, 10:16] = 1.0
    logits[2, 20:26] = 0.5
    bias[2, 20:26] = 1.0
    # row 3: every real expert at -1e30, zero bias: the selection is all ties (ids 0..5), weights 0
    logits[3] = -1e30
    rts = [ref.route(logits[r:r + 1], bias[r], TOPK) for r in range(4)]
    out.append("// (c) route: logits and bias fp32 [4][384]; ids [4][6] ascending, weights fp32 [4][6], gap fp32 [4]")
    out.append(hexs("kRouteLogits", bits32(logits), 8))
    out.append(hexs("kRouteBias", bits32(bias), 8))
    out.append(hexs("kRouteIds", torch.cat([r.ids[0] for r in rts]).tolist(), 8))
    out.append(hexs("kRouteW", bits32(torch.cat([r.weights[0] for r in rts])), 8))
    out.append(hexs("kRouteGap", bits32(torch.cat([r.gap for r in rts])), 8))

    # (d) the combine: 6 expert rows (fine, t 6 + j, seed 7) + the shared row (t 12), route row 0's weights
    rt = rts[0]
    ys = {int(e): vec(False, 6 + j, D, 7).to(torch.bfloat16)[None] for j, e in enumerate(rt.ids[0].tolist())}
    sh = vec(False, 12, D, 7).to(torch.bfloat16)[None]
    mo = ref.moe(ops, torch.zeros(1, D, dtype=torch.bfloat16), rt, lambda e, xs: ys[e], lambda xs: sh)[0]
    out.append("// (d) combine: route row 0, y_j = fine (t 6 + j, seed 7) for slot j, shared fine (t 12); bf16 [2560]")
    out.append(hexs("kCombine", bits16(mo), 4))

    # (e) eager attention, GQA 12 on one kv head
    out.append(f"// (e) eager attention: {ATTN_HEADS} q heads / 1 kv head; q coarse (t 20, seed = case, step 1/2),")
    out.append("//     key p: k / v coarse (t 21 / 22, seed 9, step 1/8) at index p x 128 + d. Head 0's scores s and")
    out.append("//     probabilities p over the row's keys [lo, hi] (bf16), every head's output o [12][128] (bf16)")
    out.append(f"inline constexpr unsigned kAttnCases = {len(ATTN_CASES)}, kAttnHeads = {ATTN_HEADS};")
    meta = []
    for ci, (name, sliding, qp, lo, hi) in enumerate(ATTN_CASES):
        L = hi - lo + 1
        q = vec(True, 20, ATTN_HEADS * HD, ci, step=0.5).reshape(1, ATTN_HEADS, 1, HD).to(torch.bfloat16)
        k = torch.stack([vec(True, 21, HD, 9, base=p * HD) for p in range(lo, hi + 1)])[None, None].to(torch.bfloat16)
        v = torch.stack([vec(True, 22, HD, 9, base=p * HD) for p in range(lo, hi + 1)])[None, None].to(torch.bfloat16)
        q_idx = torch.tensor([qp])
        k_idx = torch.arange(lo, hi + 1)
        ok = ref.visible(q_idx, k_idx, 513 if sliding else None)
        o = ref.attention(ops, q, k, v, ok, ATTN_HEADS)[0, 0]              # [12 x 128]
        # attention()'s own lines, for the intermediates (held to its output)
        kk = k.repeat_interleave(ATTN_HEADS, dim=1)
        vv = v.repeat_interleave(ATTN_HEADS, dim=1)
        s = torch.matmul(q, kk.transpose(2, 3)) * (HD ** -0.5)
        s = s + torch.where(ok, 0.0, torch.finfo(s.dtype).min).to(s.dtype)
        p = torch.softmax(s, dim=-1, dtype=torch.float32).to(q.dtype)
        o2 = torch.matmul(p, vv).transpose(1, 2).reshape(1, 1, ATTN_HEADS * HD)[0, 0]
        assert torch.equal(o, o2), name
        nvis = int(ok.sum())
        meta.append(f"{{{1 if sliding else 0}, {qp}, {lo}, {hi}, {nvis}}}")
        out.append(f"// {name}: query {qp}, keys [{lo}, {hi}] ({L} in the row, {nvis} visible)")
        out.append(hexs(f"kAttnS_{name}", bits16(s[0, 0, 0, :nvis]), 4))
        out.append(hexs(f"kAttnP_{name}", bits16(p[0, 0, 0, :nvis]), 4))
        out.append(hexs(f"kAttnO_{name}", bits16(o), 4))
    out.append("struct AttnCase { unsigned sliding, query, lo, hi, visible; const char* s; const char* p; const char* o; };")
    out.append("inline constexpr AttnCase kAttn[] = {")
    for (name, *_), m in zip(ATTN_CASES, meta):
        out.append(f"    {{{m[1:-1]}, kAttnS_{name}, kAttnP_{name}, kAttnO_{name}}},")
    out.append("};")
    out.append("}  // namespace kolibri_fixture")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
