#!/usr/bin/env python3
"""Spec 21b Task 4: the PLE hash's fixture for tests/loader/qwen4exp_ple_test.cc, from transformers 5.19.0.

    qwen4exp_ple_fixture.py <the original's config.json> [tests/loader/qwen4exp_ple_fixture.h]

Run once in agnes-ref-img with 21a's 5.19.0 site first on PYTHONPATH; the output is committed. Every number
is transformers' own:

  tables   for ngram_vocab_size_base 20,000,000 (the real checkpoint) and 1000 (make_synth.py's reduced base):
           the multipliers (`_build_layer_multipliers`), the 16 head sizes (`_find_nth_prime_after`, the
           constructor's walk), the offsets, the total and the padded row count
  cases    64 token sequences (EOS 248044 at every slot of short ones, a missing predecessor at positions 0
           and 1, the ids 0 and 248319, random ones) with the 16 row ids of their LAST token under each table,
           from `Qwen4ExpTextNGramEmbedding.forward` itself (its embedding replaced by a recorder - the ids are
           what the module would gather), cross-checked against qwen4exp_ref.ple_hash_ids
"""
import importlib.util
import json
import math
import os
import random
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or os.getcwd()) != _HERE]

import torch  # noqa: E402


def _load(name: str):
    spec = importlib.util.spec_from_file_location(f"q4fix_{name}", os.path.join(_HERE, f"{name}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


ref = _load("qwen4exp_ref")
EOS = 248044
VOCAB = 248320


class Recorder(torch.nn.Module):
    """Stands in for ngram_embedding: records the ids, returns zeros (the device check reads `.weight`)."""

    def __init__(self, dim: int):
        super().__init__()
        self.weight = torch.empty(0)
        self.dim = dim
        self.ids = None

    def forward(self, ids):
        self.ids = ids.clone()
        return torch.zeros(*ids.shape, self.dim)


def module(text: dict, base: int):
    ref.require_version()
    from transformers.models.qwen4_exp import modeling_qwen4_exp as M
    from transformers.models.qwen4_exp.configuration_qwen4_exp import Qwen4ExpTextConfig
    d = dict(text)
    d.pop("quantization_config", None)
    d["ngram_vocab_size_base"] = base
    tc = Qwen4ExpTextConfig(**d)
    heads = (tc.ngram_size - 1) * tc.heads_per_ngram
    with torch.device("meta"):
        m = M.Qwen4ExpTextNGramEmbedding(tc, tc.ple_embed_dim, layer_idx=1, ple_layer_index=0)
    m.layer_multipliers = M._build_layer_multipliers(tc.vocab_size, tc.ngram_size, 0, tc.seed)
    m.ngram_heads_vocab_sizes = torch.tensor(m.head_vocab_sizes, dtype=torch.long)
    m.ngram_heads_offsets = torch.tensor(m.head_offsets, dtype=torch.long)
    m.ngram_embedding = Recorder(tc.ple_embed_dim // heads)
    padded = math.ceil(m.total_vocab_size / tc.make_ngram_vocab_size_divisible_by) * tc.make_ngram_vocab_size_divisible_by
    return m, tc, padded


def cases() -> list[list[int]]:
    rng = random.Random(21)
    out = [[0], [VOCAB - 1], [EOS], [12345], [EOS, 7], [7, EOS], [5, 9], [EOS, EOS], [0, VOCAB - 1, 3]]
    for n in (3, 4, 5):
        for slot in range(n):
            seq = [rng.randrange(VOCAB) for _ in range(n)]
            seq[slot] = EOS
            out.append(seq)
    out += [[1, EOS, 2, 3], [1, 2, EOS, 3], [EOS, 1, 2, 3], [4, 5, 6, EOS, EOS, 8], [VOCAB - 1, VOCAB - 1, VOCAB - 1]]
    while len(out) < 64:
        n = rng.randrange(1, 7)
        out.append([EOS if rng.random() < 0.2 else rng.randrange(VOCAB) for _ in range(n)])
    return out[:64]


def ids_of(m, seq: list[int]) -> list[int]:
    m(torch.tensor([seq], dtype=torch.long), None)
    got = [int(x) for x in m.ngram_embedding.ids[0, -1]]
    mine = ref.ple_hash_ids(torch.tensor(seq), m.layer_multipliers, m.ngram_heads_vocab_sizes, m.ngram_heads_offsets,
                            EOS)[-1].tolist()
    if got != mine:
        raise SystemExit(f"qwen4exp_ref.ple_hash_ids differs from transformers on {seq}: {mine} vs {got}")
    return got


def main() -> None:
    with open(sys.argv[1], encoding="utf-8") as f:
        cfg = json.load(f)
    text = cfg.get("text_config", cfg)
    tables = []
    seqs = cases()
    ids = {}
    for base in (20000000, 1000):
        m, tc, padded = module(text, base)
        tables.append((base, [int(x) for x in m.layer_multipliers], m.head_vocab_sizes, m.head_offsets,
                       m.total_vocab_size, padded))
        ids[base] = [ids_of(m, s) for s in seqs]
    o = ["// Generated by tools/oracle/qwen4exp_ple_fixture.py from transformers 5.19.0's own PLE hash",
         "// (modeling_qwen4_exp.py: _build_layer_multipliers, _find_nth_prime_after, Qwen4ExpTextNGramEmbedding.forward)",
         "// - do not edit; regenerate (tools/oracle/README.md). tests/loader/qwen4exp_ple_test.cc holds",
         "// loader/qwen4exp_ple_hash.h to it exactly.",
         "#pragma once", "#include <cstdint>", "", "namespace q4ple_fixture {", "",
         "struct Table {", "  uint64_t base;", "  uint64_t mult[3];", "  uint64_t sizes[16];", "  uint64_t offsets[16];",
         "  uint64_t total, padded;", "};", "inline constexpr Table kTables[2] = {"]
    for base, mult, sizes, offs, total, padded in tables:
        o.append(f"    {{{base}ull, {{{', '.join(f'{x}ull' for x in mult)}}},")
        o.append(f"     {{{', '.join(f'{x}ull' for x in sizes)}}},")
        o.append(f"     {{{', '.join(f'{x}ull' for x in offs)}}},")
        o.append(f"     {total}ull, {padded}ull}},")
    o += ["};", "", "// A token sequence and the 16 ids of its LAST token under kTables[0] (ids[0]) and kTables[1] (ids[1]).",
          "struct Case {", "  uint32_t n;", "  uint32_t seq[6];", "  uint64_t ids[2][16];", "};",
          f"inline constexpr uint32_t kEos = {EOS};", "inline constexpr Case kCases[64] = {"]
    for i, s in enumerate(seqs):
        pad = s + [0] * (6 - len(s))
        o.append(f"    {{{len(s)}, {{{', '.join(str(x) for x in pad)}}},")
        o.append(f"     {{{{{', '.join(f'{x}ull' for x in ids[20000000][i])}}},")
        o.append(f"      {{{', '.join(f'{x}ull' for x in ids[1000][i])}}}}}}},")
    o += ["};", "", "}  // namespace q4ple_fixture", ""]
    if len(sys.argv) > 2:
        with open(sys.argv[2], "w", encoding="utf-8") as f:
            f.write("\n".join(o))
    else:
        sys.stdout.write("\n".join(o))


if __name__ == "__main__":
    main()
