#include "l0/error.h"

namespace l0 {
const char* result_name(ze_result_t r) {
  switch (r) {
#define C(x) case x: return #x;
    C(ZE_RESULT_SUCCESS) C(ZE_RESULT_NOT_READY) C(ZE_RESULT_ERROR_DEVICE_LOST)
    C(ZE_RESULT_ERROR_OUT_OF_HOST_MEMORY) C(ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)
    C(ZE_RESULT_ERROR_MODULE_BUILD_FAILURE) C(ZE_RESULT_ERROR_MODULE_LINK_FAILURE)
    C(ZE_RESULT_ERROR_UNINITIALIZED) C(ZE_RESULT_ERROR_UNSUPPORTED_VERSION)
    C(ZE_RESULT_ERROR_UNSUPPORTED_FEATURE) C(ZE_RESULT_ERROR_INVALID_ARGUMENT)
    C(ZE_RESULT_ERROR_INVALID_NULL_HANDLE) C(ZE_RESULT_ERROR_HANDLE_OBJECT_IN_USE)
    C(ZE_RESULT_ERROR_INVALID_NULL_POINTER) C(ZE_RESULT_ERROR_INVALID_SIZE)
    C(ZE_RESULT_ERROR_UNSUPPORTED_SIZE) C(ZE_RESULT_ERROR_UNSUPPORTED_ALIGNMENT)
    C(ZE_RESULT_ERROR_INVALID_SYNCHRONIZATION_OBJECT) C(ZE_RESULT_ERROR_INVALID_ENUMERATION)
    C(ZE_RESULT_ERROR_UNSUPPORTED_ENUMERATION) C(ZE_RESULT_ERROR_UNSUPPORTED_IMAGE_FORMAT)
    C(ZE_RESULT_ERROR_INVALID_NATIVE_BINARY) C(ZE_RESULT_ERROR_INVALID_GLOBAL_NAME)
    C(ZE_RESULT_ERROR_INVALID_KERNEL_NAME) C(ZE_RESULT_ERROR_INVALID_FUNCTION_NAME)
    C(ZE_RESULT_ERROR_INVALID_GROUP_SIZE_DIMENSION) C(ZE_RESULT_ERROR_INVALID_GLOBAL_WIDTH_DIMENSION)
    C(ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_INDEX) C(ZE_RESULT_ERROR_INVALID_KERNEL_ARGUMENT_SIZE)
    C(ZE_RESULT_ERROR_INVALID_KERNEL_ATTRIBUTE_VALUE) C(ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED)
    C(ZE_RESULT_ERROR_INVALID_COMMAND_LIST_TYPE) C(ZE_RESULT_ERROR_OVERLAPPING_REGIONS)
    C(ZE_RESULT_ERROR_UNKNOWN)
#undef C
    default: {
      static thread_local char buf[32];
      std::snprintf(buf, sizeof buf, "ze_result_t(0x%x)", static_cast<unsigned>(r));
      return buf;
    }
  }
}
}  // namespace l0
