#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Stage `calib` of tools/quantize_kolibri1.sh: the calibration set and the held-out evaluation sets
exactly per spec 20 §3.1.

    calib.py --model <snapshot> --out <dir> [--nsamples 1024] [--seqlen 2048] [--backend auto|vllm|hf]

Rows are SEQLEN tokens, every one starting at a conversation boundary (common.pack), all
chat-formatted through the model's own template (reasoning on: the template's default, effort
"high"). Base mix by rows (common.CAT_FRACTIONS): German 50 % (chat 20 %, tool calls 10 %, long
documents 20 %), English chat 30 %, code 20 %. The assistant turns are self-generated by the bf16
model with its published sampling (T 1.0, top-p 0.97, top-k 128): German / English / code prompts
from prompts/*.jsonl (their `calib` split); tool scenarios run two turns (the model's <tool_call>,
the scenario's canned <tool_response>, the model's answer); document rows put a German Wikipedia
article (pinned revision, shard 00000) under one of prompts/de_doc_tasks.jsonl's instructions.

Held-out sets for `eval` (never calibrated on): de_wiki - raw article text from shard 00019; de_chat,
en_chat, code - the prompts' `eval` split, answered the same way. Writes calib.safetensors,
eval_<set>.safetensors and calib_manifest.json under --out.
"""
import argparse
import os
import random
import re
import sys
import zlib

import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C  # noqa: E402


# --------------------------------------------------------------------------------------------
# generation backends

class HFGenerator:
    """The transformers port (via the shim), batched with left padding."""

    def __init__(self, shim: str, device: str, batch: int):
        from transformers import AutoModelForCausalLM
        kw = {"trust_remote_code": True, "dtype": torch.bfloat16}
        if device == "cuda":
            kw["device_map"] = "auto"
        self.model = AutoModelForCausalLM.from_pretrained(shim, **kw).eval()
        if device not in ("cpu", "cuda"):
            self.model.to(device)
        self.device = self.model.device
        self.batch = batch
        self.name = f"hf (third_party/kolibri1 port, {device}, batch {batch})"

    @torch.no_grad()
    def generate(self, prompts: list, max_new: int, seed: int) -> list:
        out = []
        for b in range(0, len(prompts), self.batch):
            chunk = prompts[b:b + self.batch]
            L = max(map(len, chunk))
            ids = torch.tensor([[C.ENDOFTEXT] * (L - len(p)) + p for p in chunk], device=self.device)
            am = torch.tensor([[0] * (L - len(p)) + [1] * len(p) for p in chunk], device=self.device)
            torch.manual_seed(seed + b)
            g = self.model.generate(input_ids=ids, attention_mask=am, do_sample=True, max_new_tokens=max_new,
                                    eos_token_id=list(C.EOS_IDS), pad_token_id=C.ENDOFTEXT, **C.SAMPLING)
            for row in g[:, L:].tolist():
                cut = next((i for i, t in enumerate(row) if t in C.EOS_IDS), None)
                out.append(row if cut is None else row[: cut + 1])
        return out


class VLLMGenerator:
    """vLLM with Aleph Alpha's plugin (`pip install aleph-alpha-inference`), on the original snapshot."""

    def __init__(self, snapshot: str, tp: int, max_len: int):
        from vllm import LLM
        self.llm = LLM(model=snapshot, tensor_parallel_size=tp, max_model_len=max_len, dtype="bfloat16", seed=0)
        self.name = f"vllm (aleph-alpha-inference plugin, tp {tp})"

    def generate(self, prompts: list, max_new: int, seed: int) -> list:
        from vllm import SamplingParams
        try:
            from vllm.inputs import TokensPrompt
        except ImportError:
            from vllm import TokensPrompt
        sps = [SamplingParams(max_tokens=max_new, seed=seed + i, stop_token_ids=list(C.EOS_IDS), **C.SAMPLING)
               for i in range(len(prompts))]
        outs = self.llm.generate([TokensPrompt(prompt_token_ids=p) for p in prompts], sps)
        res = []
        for o in outs:
            t = list(o.outputs[0].token_ids)
            if o.outputs[0].finish_reason == "stop" and (not t or t[-1] not in C.EOS_IDS):
                t.append(C.IM_END)
            res.append(t)
        return res


def make_generator(backend: str, snapshot: str, shim: str, device: str, batch: int, tp: int, max_len: int):
    if backend in ("auto", "vllm"):
        try:
            import vllm  # noqa: F401
            import aleph_alpha_inference  # noqa: F401
            return VLLMGenerator(snapshot, tp, max_len)
        except ImportError as e:
            if backend == "vllm":
                raise SystemExit(f"--backend vllm: {e} (pip install aleph-alpha-inference)")
            C.log(f"vLLM + aleph-alpha-inference not importable ({e}); generating with the transformers port")
    return HFGenerator(shim, device, batch)


# --------------------------------------------------------------------------------------------
# conversations

TOOL_CALL = re.compile(r"<tool_call>\s*(\{.*?\})\s*</tool_call>", re.S)


def parse_tool_calls(text: str) -> list:
    """Function names of the well-formed (JSON, hermes-style) calls in a generated turn."""
    import json
    names = []
    for m in TOOL_CALL.finditer(text):
        try:
            obj = json.loads(m.group(1))
        except ValueError:
            continue
        if isinstance(obj, dict) and isinstance(obj.get("name"), str):
            names.append(obj["name"])
    return names


def render(tok, messages, tools=None, gen_prompt=True) -> list:
    text = tok.apply_chat_template(messages, tools=tools, tokenize=False, add_generation_prompt=gen_prompt)
    return tok(text, add_special_tokens=False)["input_ids"]


def tool_response_ids(tok, names: list, results: dict) -> list:
    """The template's tool turn for these calls, then the next assistant header."""
    body = "".join("\n<tool_response>\n" + results.get(n, '{"status": "ok"}') + "\n</tool_response>" for n in names)
    return tok("\n<|im_start|>user" + body + "<|im_end|>\n<|im_start|>assistant\n", add_special_tokens=False)["input_ids"]


def truncate_text(tok, text: str, n_tokens: int) -> str:
    ids = tok(text, add_special_tokens=False)["input_ids"]
    return text if len(ids) <= n_tokens else tok.decode(ids[:n_tokens])


class Builder:
    def __init__(self, tok, gen, a, rng):
        self.tok, self.gen, self.a, self.rng = tok, gen, a, rng
        self.stats = {"generated_tokens": 0, "tool_turns": 0, "tool_calls_parsed": 0, "conversations": 0}

    def _gen(self, prompts, max_new, seed):
        outs = self.gen.generate(prompts, max_new, seed)
        self.stats["generated_tokens"] += sum(map(len, outs))
        return outs

    def chat(self, rows: list, seed: int) -> list:
        """One answered conversation per prompt row ({"prompt"})."""
        ps = [render(self.tok, [{"role": "user", "content": r["prompt"]}]) for r in rows]
        gs = self._gen(ps, self.a.gen_max, seed)
        self.stats["conversations"] += len(ps)
        return [p + g for p, g in zip(ps, gs)]

    def tools(self, rows: list, seed: int) -> list:
        ps = [render(self.tok, [{"role": "user", "content": r["prompt"]}], tools=r["tools"]) for r in rows]
        g1 = self._gen(ps, self.a.gen_max, seed)
        convs, second, idx = [p + g for p, g in zip(ps, g1)], [], []
        for i, (r, g) in enumerate(zip(rows, g1)):
            names = parse_tool_calls(self.tok.decode(g))
            self.stats["tool_calls_parsed"] += len(names)
            if names and g and g[-1] == C.IM_END:
                second.append(convs[i] + tool_response_ids(self.tok, names, r["tool_results"]))
                idx.append(i)
        if second:
            g2 = self._gen(second, self.a.gen_max, seed + 7919)
            self.stats["tool_turns"] += len(second)
            for i, s, g in zip(idx, second, g2):
                convs[i] = s + g
        self.stats["conversations"] += len(ps)
        return convs

    def docs(self, docs: list, tasks: list, seed: int) -> list:
        ps = []
        for d in docs:
            task = self.rng.choice(tasks)["prompt"]
            body = truncate_text(self.tok, d["text"], self.a.doc_tokens)
            ps.append(render(self.tok, [{"role": "user", "content": f"{task}\n\n{d['title']}\n\n{body}"}]))
        gs = self._gen(ps, self.a.doc_gen_max, seed)
        self.stats["conversations"] += len(ps)
        return [p + g for p, g in zip(ps, gs)]


def fill(name: str, n_rows: int, make_round, seqlen: int, max_rounds: int):
    """Conversations from make_round(r) until they pack into n_rows rows."""
    convs = []
    for r in range(max_rounds):
        if n_rows == 0:
            break
        new = make_round(r)
        if not new:
            break
        convs += new
        rows, starts = C.pack(convs, n_rows, seqlen)
        C.log(f"{name}: round {r}: {len(convs)} conversations, {sum(map(len, convs))} tokens -> {len(rows)}/{n_rows} rows")
        if len(rows) >= n_rows:
            return rows, convs
    rows, _ = C.pack(convs, n_rows, seqlen)
    if len(rows) < n_rows:
        raise SystemExit(f"{name}: only {len(rows)} of {n_rows} rows after {max_rounds} rounds - raise --max-rounds")
    return rows, convs


def doc_rounds(it, used: list, per_round: int):
    def take():
        out = []
        for d in it:
            out.append(d)
            used.append(d["id"])
            if len(out) == per_round:
                break
        return out
    return take


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", required=True, help="the bf16 snapshot directory")
    ap.add_argument("--shim", help="the shim directory (default <out>/shim)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--nsamples", type=int, default=1024, help="base calibration rows (before the coverage top-up)")
    ap.add_argument("--seqlen", type=int, default=C.SEQLEN)
    ap.add_argument("--eval-rows", type=int, default=32, help="rows per held-out set")
    ap.add_argument("--backend", choices=("auto", "vllm", "hf"), default="auto")
    ap.add_argument("--device", default="cpu", help="hf backend: cpu | cuda | xpu")
    ap.add_argument("--batch", type=int, default=16, help="hf backend batch")
    ap.add_argument("--tp", type=int, default=int(os.environ.get("KOLIBRI_TP", "1")), help="vllm tensor parallel size")
    ap.add_argument("--gen-max", type=int, default=1536, help="max new tokens per chat / code / tool turn")
    ap.add_argument("--doc-gen-max", type=int, default=768, help="max new tokens per document answer")
    ap.add_argument("--doc-tokens", type=int, default=1200, help="document tokens per de_doc conversation")
    ap.add_argument("--docs-per-round", type=int, default=64)
    ap.add_argument("--max-rounds", type=int, default=64)
    ap.add_argument("--seed", type=int, default=20261005)
    ap.add_argument("--prompts", default=C.PROMPTS)
    a = ap.parse_args()

    snapshot = C.resolve_model(a.model)
    shim = C.make_shim(snapshot, a.shim or os.path.join(a.out, "shim"))
    tok = C.load_tokenizer(snapshot)
    rng = random.Random(a.seed)
    P = {n: C.read_jsonl(os.path.join(a.prompts, n + ".jsonl"))
         for n in ("de_chat", "en_chat", "code", "de_tools", "de_doc_tasks")}
    split = {n: {s: [r for r in rows if r["split"] == s] for s in ("calib", "eval")} for n, rows in P.items()}
    gen = make_generator(a.backend, snapshot, shim, a.device, a.batch, a.tp, a.seqlen + max(a.gen_max, a.doc_gen_max) * 2 + 4096)
    C.log(f"generator: {gen.name}")
    b = Builder(tok, gen, a, rng)
    want = {c: round(a.nsamples * f) for c, f in C.CAT_FRACTIONS.items()}
    want["en_chat"] += a.nsamples - sum(want.values())
    C.log(f"rows wanted: {want} (x {a.seqlen} tokens)")

    def prompt_round(key, fn, sp="calib"):
        def mk(r):
            rows = list(split[key][sp])
            random.Random(a.seed + r).shuffle(rows)
            return fn(rows, a.seed + 1000 * r + zlib.crc32(key.encode()) % 997)
        return mk

    used_calib_docs, used_eval_docs = [], []
    rows_by_cat, n_convs = {}, {}
    for cat, key, fn in (("de_chat", "de_chat", b.chat), ("en_chat", "en_chat", b.chat), ("code", "code", b.chat),
                         ("de_tool", "de_tools", b.tools)):
        rows_by_cat[cat], convs = fill(cat, want[cat], prompt_round(key, fn), a.seqlen, a.max_rounds)
        n_convs[cat] = len(convs)
    take = doc_rounds(C.iter_docs("calib"), used_calib_docs, a.docs_per_round)
    rows_by_cat["de_doc"], convs = fill("de_doc", want["de_doc"],
                                        lambda r: b.docs(take(), split["de_doc_tasks"]["calib"], a.seed + 77 * r),
                                        a.seqlen, a.max_rounds)
    n_convs["de_doc"] = len(convs)

    ids, cats = [], []
    for c in C.CAT_FRACTIONS:
        ids += rows_by_cat[c]
        cats += [c] * len(rows_by_cat[c])
    order = list(range(len(ids)))
    random.Random(a.seed).shuffle(order)
    ids_t = torch.tensor([ids[i] for i in order], dtype=torch.long)
    cats = [cats[i] for i in order]
    lang = {lg: sum(1 for c in cats if C.CAT_LANG[c] == lg) / len(cats) for lg in ("de", "en", "code")}
    meta = {"stage": "calib", "rows": len(cats), "seqlen": a.seqlen, "rows_by_cat": {c: cats.count(c) for c in C.CAT_FRACTIONS},
            "token_share": lang}
    C.save_rows(os.path.join(a.out, "calib.safetensors"), ids_t, cats, meta)
    C.log(f"calib.safetensors: {len(cats)} rows x {a.seqlen} = {len(cats) * a.seqlen} tokens; share {lang}")

    # held-out sets ------------------------------------------------------------------------------
    eval_info = {}
    for name, key, fn in (("de_chat", "de_chat", b.chat), ("en_chat", "en_chat", b.chat), ("code", "code", b.chat)):
        rows, convs = fill(f"eval {name}", a.eval_rows, prompt_round(key, fn, "eval"), a.seqlen, a.max_rounds)
        C.save_rows(os.path.join(a.out, f"eval_{name}.safetensors"), torch.tensor(rows), [name] * len(rows),
                    {"set": name, "prompts": [r["id"] for r in split[key]["eval"]]})
        eval_info[name] = {"rows": len(rows), "conversations": len(convs)}
    sep = tok("\n\n", add_special_tokens=False)["input_ids"]
    wiki = []
    for d in C.iter_docs("eval"):
        wiki.append(tok(d["text"], add_special_tokens=False)["input_ids"] + sep)
        used_eval_docs.append(d["id"])
        rows, _ = C.pack(wiki, a.eval_rows, a.seqlen)
        if len(rows) >= a.eval_rows:
            break
    rows, _ = C.pack(wiki, a.eval_rows, a.seqlen)
    if len(rows) < a.eval_rows:
        raise SystemExit(f"de_wiki: only {len(rows)} rows from the evaluation documents")
    C.save_rows(os.path.join(a.out, "eval_de_wiki.safetensors"), torch.tensor(rows), ["de_wiki"] * len(rows),
                {"set": "de_wiki", "format": "raw article text, no chat template"})
    eval_info["de_wiki"] = {"rows": len(rows), "documents": len(used_eval_docs)}
    overlap = set(used_calib_docs) & set(used_eval_docs)
    if overlap:
        raise SystemExit(f"evaluation documents overlap the calibration ones: {sorted(overlap)[:5]}")

    manifest = {
        "model": a.model, "snapshot": snapshot, "seqlen": a.seqlen, "nsamples_base": a.nsamples,
        "rows_by_cat": meta["rows_by_cat"], "token_share": lang, "conversations": n_convs,
        "generator": gen.name, "sampling": C.SAMPLING, "gen_max": a.gen_max, "doc_gen_max": a.doc_gen_max,
        "doc_tokens": a.doc_tokens, "reasoning": "on (template default, effort high)", "seed": a.seed,
        "stats": b.stats, "documents": C.doc_source(), "calib_doc_ids": used_calib_docs,
        "eval_doc_ids": used_eval_docs, "eval_sets": eval_info,
        "prompt_files": {n: C.sha256_file(os.path.join(a.prompts, n + ".jsonl")) for n in P},
        "prompt_split": {n: {s: len(v) for s, v in d.items()} for n, d in split.items()},
    }
    C.write_json(os.path.join(a.out, "calib_manifest.json"), manifest)
    C.log(f"stats {b.stats}; eval sets {eval_info}")


if __name__ == "__main__":
    main()
