// Spec 21b Task 4: the PLE table's host half (loader/qwen4exp_ple_hash.h, loader/qwen4exp_ple.h), host only.
//
//   1. the hash in exact integers (Review Focus 3): q4_ple_multipliers, q4_ple_primes and the offsets equal
//      transformers 5.19.0's own builders for base 20,000,000 (the checkpoint's - and 21a's facts sheet's I64
//      tensors) and for make_synth.py's 1000; q4_ple_history + q4_ple_ids give the 16 ids transformers'
//      Qwen4ExpTextNGramEmbedding.forward computes for the last token of 64 sequences (EOS at every slot, a
//      missing predecessor, the ids 0 and 248319) - tests/loader/qwen4exp_ple_fixture.h, generated by
//      tools/oracle/qwen4exp_ple_fixture.py;
//   2. Q4PleHost over a test-written file in ple_int8.py's format (2 heads of small primes, both scale dtypes):
//      marker rows at head-local indices, the scale dtype read, dequant_row = bf16(float(q) x float(s));
//   3. check_q4_ple against a test descriptor (2 heads, base 50): passes, and refuses a wrong multiplier, a
//      wrong size, a wrong offset, a wrong width, a wrong head count - each naming the tensor;
//   4. the host-memory rule refuses naming both numbers; q4_ple_dir finds <snapshot>-ple-int8/ or $B70_Q4_PLE
//      and refuses naming ple_int8.py;
//   5. the real table's derived bytes (51.2 GB of q + 0.64 / 1.28 GB of scales) printed.
#include <unistd.h>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <string>
#include <vector>

#include "check.h"
#include "common/bf16.h"
#include "loader/qwen4exp_ple.h"
#include "loader/qwen4exp_ple_hash.h"
#include "model/qwen4exp.h"
#include "qwen4exp_ple_fixture.h"

namespace {

namespace fs = std::filesystem;

struct Tensor {
  std::string dtype;
  std::vector<uint64_t> shape;
  std::vector<uint8_t> bytes;
};
using Tensors = std::map<std::string, Tensor>;

void write_checkpoint(const fs::path& dir, const Tensors& ts) {
  fs::create_directories(dir);
  std::string hdr = "{\"__metadata__\":{\"rule\":\"row-int8-spec9\"}";
  uint64_t off = 0;
  for (const auto& [name, t] : ts) {
    hdr += ",\"" + name + "\":{\"dtype\":\"" + t.dtype + "\",\"shape\":[";
    for (size_t i = 0; i < t.shape.size(); ++i) hdr += (i ? "," : "") + std::to_string(t.shape[i]);
    hdr += "],\"data_offsets\":[" + std::to_string(off) + "," + std::to_string(off + t.bytes.size()) + "]}";
    off += t.bytes.size();
    off = (off + 7) / 8 * 8;
  }
  hdr += "}";
  while ((8 + hdr.size()) % 8 != 0) hdr += ' ';
  std::ofstream f(dir / "ple_int8-00001-of-00001.safetensors", std::ios::binary);
  const uint64_t hlen = hdr.size();
  f.write(reinterpret_cast<const char*>(&hlen), 8);
  f.write(hdr.data(), std::streamsize(hdr.size()));
  uint64_t pos = 0;
  for (const auto& [name, t] : ts) {
    (void)name;
    f.write(reinterpret_cast<const char*>(t.bytes.data()), std::streamsize(t.bytes.size()));
    pos += t.bytes.size();
    const uint64_t pad = (pos + 7) / 8 * 8 - pos;
    const char zeros[8] = {};
    f.write(zeros, std::streamsize(pad));
    pos += pad;
  }
  std::ofstream ix(dir / "model.safetensors.index.json");
  ix << "{\"metadata\":{},\"weight_map\":{";
  bool first = true;
  for (const auto& [name, t] : ts) {
    (void)t;
    ix << (first ? "" : ",") << "\"" << name << "\":\"ple_int8-00001-of-00001.safetensors\"";
    first = false;
  }
  ix << "}}";
}

template <class T>
Tensor make(const std::string& dtype, std::vector<uint64_t> shape, const std::vector<T>& v) {
  Tensor t{dtype, std::move(shape), std::vector<uint8_t>(v.size() * sizeof(T))};
  std::memcpy(t.bytes.data(), v.data(), t.bytes.size());
  return t;
}

template <class F>
void throws_naming(const std::string& what, F fn) {
  bool ok = false;
  try {
    fn();
  } catch (const std::exception& e) {
    ok = std::string(e.what()).find(what) != std::string::npos;
    if (!ok) std::fprintf(stderr, "threw, but without '%s': %s\n", what.c_str(), e.what());
  }
  if (!ok) std::fprintf(stderr, "expected a refusal naming '%s'\n", what.c_str());
  CHECK(ok);
}

// A 2-head descriptor: base 50 (heads of 53 and 59 rows), the real vocab / seed (the multipliers' inputs).
model::Qwen4ExpDesc small_desc() {
  model::Qwen4ExpDesc d = model::qwen4exp();
  d.ple_heads = 2;
  d.ple_base = 50;
  return d;
}

// The file of `d`'s 2 heads: row r of head h holds q[i] = (h * 31 + r + i) % 255 - 127, s = 0.5 + r / 64 (a
// marker the reader must return at head-local row r); the I64 tensors by the formula unless overridden.
Tensors ple_file(const model::Qwen4ExpDesc& d, bool bf16_scale, std::vector<uint64_t> mult = {},
                 std::vector<uint64_t> sizes = {}, std::vector<uint64_t> offs = {}, uint32_t dim = 160) {
  const std::vector<uint64_t> p = loader::q4_ple_primes(d.ple_base, d.ple_heads, 0);
  if (mult.empty()) {
    const auto m = loader::q4_ple_multipliers(d.vocab, d.ngram, 0, d.ple_seed);
    mult.assign(m.begin(), m.end());
  }
  if (sizes.empty()) sizes = p;
  if (offs.empty()) offs = loader::q4_ple_offsets(p);
  Tensors ts;
  for (uint32_t h = 0; h < d.ple_heads; ++h) {
    std::vector<int8_t> q(size_t(p[h]) * dim);
    std::vector<float> sf(p[h]);
    std::vector<uint16_t> sb(p[h]);
    for (uint64_t r = 0; r < p[h]; ++r) {
      for (uint32_t i = 0; i < dim; ++i) q[size_t(r) * dim + i] = int8_t(int((h * 31 + r + i) % 255) - 127);
      sf[r] = 0.5f + float(r) / 64.0f;
      sb[r] = common::f32_to_bf16(sf[r]);
    }
    ts["ple.h" + std::to_string(h) + ".q"] = make("I8", {p[h], dim}, q);
    ts["ple.h" + std::to_string(h) + ".s"] = bf16_scale ? make("BF16", {p[h]}, sb) : make("F32", {p[h]}, sf);
  }
  const auto i64 = [](const std::vector<uint64_t>& v) {
    std::vector<int64_t> o(v.begin(), v.end());
    return make("I64", {o.size()}, o);
  };
  ts["ple.layer_multipliers"] = i64(mult);
  ts["ple.ngram_heads_vocab_sizes"] = i64(sizes);
  ts["ple.ngram_heads_offsets"] = i64(offs);
  return ts;
}

fs::path tmpdir(const std::string& tag) {
  return fs::temp_directory_path() / ("qwen4exp_ple_test_" + tag + "_" + std::to_string(::getpid()));
}

}  // namespace

int main() {
  namespace F = q4ple_fixture;
  const model::Qwen4ExpDesc& d = model::qwen4exp();

  // --- 1. the hash against transformers' own --------------------------------------------------------------
  for (const F::Table& t : F::kTables) {
    const std::array<uint64_t, 3> m = loader::q4_ple_multipliers(d.vocab, d.ngram, 0, d.ple_seed);
    for (int i = 0; i < 3; ++i) CHECK_EQ(m[i], t.mult[i]);
    const std::vector<uint64_t> p = loader::q4_ple_primes(t.base, 16, 0), o = loader::q4_ple_offsets(p);
    for (int h = 0; h < 16; ++h) {
      CHECK_EQ(p[h], t.sizes[h]);
      CHECK_EQ(o[h], t.offsets[h]);
    }
    CHECK_EQ(loader::q4_ple_total_rows(p), t.total);
    CHECK_EQ((t.total + d.ple_pad - 1) / d.ple_pad * d.ple_pad, t.padded);
  }
  // 21a's facts sheet (the checkpoint's I64 tensors, range-fetched from both repositories).
  CHECK_EQ(F::kTables[0].mult[0], uint64_t(23703573157769ull));
  CHECK_EQ(F::kTables[0].sizes[15], uint64_t(20000171));
  CHECK_EQ(F::kTables[0].total, uint64_t(320001446));
  CHECK_EQ(F::kTables[0].padded, uint64_t(320001536));
  // The multipliers never overflow: t x m < 2^63 for every id t < vocab.
  for (uint64_t m : loader::q4_ple_multipliers(d.vocab, 3, 0, 1234)) CHECK(m % 2 == 1 && (d.vocab - 1) * m < (uint64_t(1) << 63));
  size_t eos_cases = 0;
  for (const F::Case& c : F::kCases) {
    const loader::Q4PleHistory hs = loader::q4_ple_history(c.seq, c.n - 1, F::kEos);
    for (int t = 0; t < 2; ++t) {
      const F::Table& tb = F::kTables[t];
      const std::vector<uint64_t> sizes(tb.sizes, tb.sizes + 16), offs(tb.offsets, tb.offsets + 16);
      const std::array<uint64_t, 3> mult = {tb.mult[0], tb.mult[1], tb.mult[2]};
      const std::array<uint64_t, 16> ids = loader::q4_ple_ids(hs.t0, hs.t1, hs.t2, mult, sizes, offs);
      for (int h = 0; h < 16; ++h) {
        if (ids[h] != c.ids[t][h])
          std::fprintf(stderr, "case n=%u seq[0]=%u table %d head %d: %llu vs %llu\n", c.n, c.seq[0], t, h,
                       (unsigned long long)ids[h], (unsigned long long)c.ids[t][h]);
        CHECK_EQ(ids[h], c.ids[t][h]);
        CHECK(ids[h] >= tb.offsets[h] && ids[h] < tb.offsets[h] + tb.sizes[h]);
      }
    }
    for (uint32_t i = 0; i + 1 < c.n; ++i) eos_cases += c.seq[i] == F::kEos;
  }
  CHECK(eos_cases > 10);

  // --- 2. the file reader, both scale dtypes ---------------------------------------------------------------
  const model::Qwen4ExpDesc sd = small_desc();
  const std::vector<uint64_t> sp = loader::q4_ple_primes(sd.ple_base, 2, 0);
  CHECK(sp.size() == 2 && sp[0] == 53 && sp[1] == 59);
  for (bool bf16 : {false, true}) {
    const fs::path dir = tmpdir(bf16 ? "bf16" : "f32");
    write_checkpoint(dir, ple_file(sd, bf16));
    const loader::Q4PleHost h(dir.string());
    CHECK(h.scale() == (bf16 ? loader::Q4PleScale::Bf16 : loader::Q4PleScale::F32));
    CHECK(h.heads() == 2 && h.dim() == 160 && h.rows(0) == 53 && h.rows(1) == 59);
    CHECK_EQ(h.bytes(), size_t(53 + 59) * (160 + (bf16 ? 2 : 4)));
    CHECK_EQ(h.bytes(), loader::q4_ple_table_bytes(sp, 160, h.scale()));
    for (uint32_t hh = 0; hh < 2; ++hh)
      for (uint64_t r : {uint64_t(0), uint64_t(17), h.rows(hh) - 1}) {
        for (uint32_t i = 0; i < 160; ++i) CHECK(h.q(hh)[r * 160 + i] == int8_t(int((hh * 31 + r + i) % 255) - 127));
        const float want_s = 0.5f + float(r) / 64.0f;
        const float got_s = bf16 ? common::bf16_to_f32(static_cast<const uint16_t*>(h.s(hh))[r])
                                 : static_cast<const float*>(h.s(hh))[r];
        CHECK(got_s == (bf16 ? common::bf16_to_f32(common::f32_to_bf16(want_s)) : want_s));
        uint16_t row[160];
        h.dequant_row(hh, r, row);
        for (uint32_t i = 0; i < 160; ++i) CHECK(row[i] == common::f32_to_bf16(float(h.q(hh)[r * 160 + i]) * got_s));
      }
    // --- 3. the file against the descriptor ---
    loader::check_q4_ple(sd, h);
    fs::remove_all(dir);
  }
  {
    const auto m = loader::q4_ple_multipliers(sd.vocab, 3, 0, sd.ple_seed);
    const std::vector<std::pair<std::string, Tensors>> bad = {
        {"ple.layer_multipliers", ple_file(sd, true, {m[0], m[1] + 2, m[2]})},
        {"ple.ngram_heads_vocab_sizes", ple_file(sd, true, {}, {53, 61})},
        {"ple.ngram_heads_offsets", ple_file(sd, true, {}, {}, {0, 54})},
        {"rows are 128 wide", ple_file(sd, true, {}, {}, {}, 128)}};
    for (const auto& [what, ts] : bad) {
      const fs::path dir = tmpdir("bad");
      write_checkpoint(dir, ts);
      const loader::Q4PleHost h(dir.string());
      throws_naming(what, [&] { loader::check_q4_ple(sd, h); });
      fs::remove_all(dir);
    }
    model::Qwen4ExpDesc three = sd;
    three.ple_heads = 3;
    const fs::path dir = tmpdir("heads");
    write_checkpoint(dir, ple_file(sd, false));
    const loader::Q4PleHost h(dir.string());
    throws_naming("2 heads", [&] { loader::check_q4_ple(three, h); });
    model::Qwen4ExpDesc other_base = sd;
    other_base.ple_base = 1000;
    throws_naming("ngram_vocab_size_base", [&] { loader::check_q4_ple(other_base, h); });
    fs::remove_all(dir);
    // a file without ple_int8.py's names is refused naming the tensor
    const fs::path empty = tmpdir("empty");
    Tensors ts = ple_file(sd, false);
    ts.erase("ple.h1.s");
    write_checkpoint(empty, ts);
    throws_naming("ple.h1.s", [&] { loader::Q4PleHost x(empty.string()); });
    fs::remove_all(empty);
  }

  // --- 4. the host-memory rule and the directory --------------------------------------------------------------
  const size_t gib = size_t(1) << 30;
  loader::check_q4_ple_host_fit(size_t(52) * gib, size_t(70) * gib);
  loader::check_q4_ple_host_fit(size_t(52) * gib, 0);   // unknown MemAvailable: passes
  throws_naming(std::to_string(size_t(64) * gib) + " B", [&] { loader::check_q4_ple_host_fit(size_t(52) * gib, size_t(64) * gib); });
  throws_naming(std::to_string(size_t(52) * gib) + " B", [&] { loader::check_q4_ple_host_fit(size_t(52) * gib, size_t(64) * gib); });
  {
    const fs::path snap = tmpdir("snap");
    fs::create_directories(snap);
    ::unsetenv("B70_Q4_PLE");
    throws_naming("ple_int8.py", [&] { loader::q4_ple_dir(snap.string() + "/"); });
    const fs::path ple = fs::path(snap.string() + "-ple-int8");
    write_checkpoint(ple, ple_file(sd, true));
    CHECK_EQ(loader::q4_ple_dir(snap.string() + "/"), ple.string() + "/");
    const fs::path other = tmpdir("other");
    write_checkpoint(other, ple_file(sd, true));
    ::setenv("B70_Q4_PLE", other.string().c_str(), 1);
    CHECK_EQ(loader::q4_ple_dir(snap.string()), other.string() + "/");
    ::unsetenv("B70_Q4_PLE");
    fs::remove_all(snap);
    fs::remove_all(ple);
    fs::remove_all(other);
  }
  CHECK(loader::q4_ple_tag(0, 0) != loader::q4_ple_tag(1, 0) && loader::q4_ple_tag(0, 1) != loader::q4_ple_tag(0, 0));

  // --- 5. the real table's bytes (derived) --------------------------------------------------------------------
  const std::vector<uint64_t> real = loader::q4_ple_primes(d.ple_base, d.ple_heads, 0);
  const size_t f32 = loader::q4_ple_table_bytes(real, d.ple_dim, loader::Q4PleScale::F32);
  const size_t b16 = loader::q4_ple_table_bytes(real, d.ple_dim, loader::Q4PleScale::Bf16);
  CHECK_EQ(b16, size_t(320001446) * 162);
  CHECK_EQ(f32, size_t(320001446) * 164);
  std::printf("qwen4exp_ple_test OK: the hash = transformers 5.19.0's on 64 sequences x 2 tables (%zu EOS "
              "predecessors), the file read per head in both scale dtypes, every refusal by name; the real table "
              "%zu B (%.2f GB) with bf16 scales, %zu B (%.2f GB) with f32 (derived)\n",
              eos_cases, b16, b16 / 1e9, f32, f32 / 1e9);
  return 0;
}
