#!/usr/bin/env bash
# One command: Kolibri-1 (Aleph-Alpha/Kolibri-1-BF16) -> int4 g64 symmetric AutoRound, GPTQ export,
# German-first calibration - spec 20 §3.1, the operator's ruling, encoded stage by stage.
#
#   tools/quantize_kolibri1.sh [--only STAGE | --from STAGE] [--dry-run] [--list]
#
# Stages (resumable: a finished stage leaves $OUT/.done-<stage>; a rerun skips it unless --only / --from
# name it):
#   calib     calibration rows (>= 50 % German chat / tool calls / documents, ~30 % English chat, ~20 %
#             code; chat template; answers self-generated by the bf16 model, reasoning on) and the
#             held-out evaluation sets                                    tools/quantize/kolibri/calib.py
#   coverage  per-layer per-expert routed-token counts on the calibration set; experts under
#             COVERAGE_FLOOR get targeted German text; FAILS if they cannot   .../coverage.py
#   rtn       AutoRound --iters 0 (plain RTN, the baseline), per attention arm  .../autoround_run.py
#   tune      AutoRound sign-SGD --iters ITERS --nsamples (all rows) --seqlen 2048 --low_gpu_mem_usage
#   eval      KL / top-1 / perplexity vs bf16, German and English apart, against the bars  .../evaluate.py
#   check     the engine's acceptance of every export (loader rules + bf16 tensors bitwise)  .../check.py
#   card      the model card for urakozz/Kolibri-1-W4A16-g64-AutoRound-GPTQ  .../card.py
#
# Settings that are spec 20 §3.1 and not overridable: scheme W4A16, group_size 64, symmetric,
# format auto_round:auto_gptq, model dtype bf16, bf16 for the router, expert_bias, shared experts,
# norms, embed_tokens and lm_head (no --quant_lm_head), seqlen 2048 for the real run.
#
# Overridables (environment):
#   MODEL     the bf16 model: HF id or snapshot dir            (Aleph-Alpha/Kolibri-1-BF16)
#   OUT       work + output directory                          ($HOME/models/kolibri1-w4g64)
#   DEVICE    cpu | xpu | cuda: AutoRound's device_map, the reference passes, hf generation (cpu)
#   NSAMPLES  base calibration rows of SEQLEN tokens           (1024 = 2.1M tokens; spec: 1024-2048)
#   ATTN      int4 | bf16 | both - attention precision arms    (both: spec 20 decision 2 = measure both)
#   ITERS (200), SEQLEN (2048), EVAL_ROWS (32 per held-out set), COVERAGE_FLOOR (2048),
#   COVERAGE_ROUNDS (4), GEN_BACKEND (auto | vllm | hf), TP (vLLM tensor parallel, 1), ARM (card: auto),
#   BATCH (AutoRound batch size, 8), COMPILE (AutoRound torch.compile: auto | on | off),
#   GEN_MAX (1536) / DOC_GEN_MAX (768): new tokens per generated turn; DOC_TOKENS (1200) per document
#   VENVPY    python with torch (+ the device backend) and transformers >= 5.13; auto-round is
#             installed into it at AR_COMMIT on first use      ($HOME/auto-round/.venv/bin/python)
#   GEN_PY    python for the calib stage (a vLLM + aleph-alpha-inference env)   ($VENVPY)
#   AR_SRC    where auto-round comes from: a clean checkout at AR_COMMIT, or a pip URL
#             (git+https://github.com/intel/auto-round@$AR_COMMIT)
#
# The AutoRound version is NOT the Qwen3.8 scripts' pinned v0.14.2: Kolibri uses auto-round main at
# AR_COMMIT (0.17.0), checked on a tiny Kolibri: per-expert qweight/qzeros/scales complete, GPTQ v1
# layout, accepted by the check stage (docs/probe-kolibri-2026-10-05.md, tools/quantize/README.md).
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
K="$ROOT/tools/quantize/kolibri"
MODEL="${MODEL:-Aleph-Alpha/Kolibri-1-BF16}"
OUT="${OUT:-$HOME/models/kolibri1-w4g64}"
DEVICE="${DEVICE:-cpu}"
NSAMPLES="${NSAMPLES:-1024}"
ATTN="${ATTN:-both}"
ITERS="${ITERS:-200}"
SEQLEN="${SEQLEN:-2048}"
EVAL_ROWS="${EVAL_ROWS:-32}"
COVERAGE_FLOOR="${COVERAGE_FLOOR:-2048}"
COVERAGE_ROUNDS="${COVERAGE_ROUNDS:-4}"
GEN_BACKEND="${GEN_BACKEND:-auto}"
TP="${TP:-1}"
ARM="${ARM:-auto}"
BATCH="${BATCH:-8}"
COMPILE="${COMPILE:-auto}"
GEN_MAX="${GEN_MAX:-1536}"
DOC_GEN_MAX="${DOC_GEN_MAX:-768}"
DOC_TOKENS="${DOC_TOKENS:-1200}"
VENVPY="${VENVPY:-$HOME/auto-round/.venv/bin/python}"
GEN_PY="${GEN_PY:-$VENVPY}"
AR_COMMIT=6afaecdbe4092dc803f3e91026fe81a65b64b372      # intel/auto-round main, 2026-09-30, version 0.17.0
AR_SRC="${AR_SRC:-git+https://github.com/intel/auto-round@$AR_COMMIT}"
SHIM="$OUT/Kolibri-1"
STAGES=(calib coverage rtn tune eval check card)

only="" from="" dry=0
while [ $# -gt 0 ]; do
  case "$1" in
    --only) only=${2:?--only needs a stage}; shift 2 ;;
    --from) from=${2:?--from needs a stage}; shift 2 ;;
    --dry-run) dry=1; shift ;;
    --list) printf '%s\n' "${STAGES[@]}"; exit 0 ;;
    -h|--help) sed -n '2,48p' "$0"; exit 0 ;;
    *) echo "quantize_kolibri1: unknown argument $1 (see --help)" >&2; exit 2 ;;
  esac
done
for s in "$only" "$from"; do
  if [ -n "$s" ] && [[ ! " ${STAGES[*]} " == *" $s "* ]]; then
    echo "quantize_kolibri1: unknown stage '$s' (${STAGES[*]})" >&2; exit 2
  fi
done
[ -n "$only" ] && [ -n "$from" ] && { echo "--only and --from are exclusive" >&2; exit 2; }
case "$ATTN" in int4) arms=(int4) ;; bf16) arms=(bf16) ;; both) arms=(int4 bf16) ;;
  *) echo "ATTN=$ATTN: int4 | bf16 | both" >&2; exit 2 ;; esac

q() { printf '%q ' "$@"; }

# selected <stage>: 0 when this invocation runs it
selected() {
  local s=$1
  if [ -n "$only" ]; then [ "$s" = "$only" ]; return; fi
  if [ -n "$from" ]; then
    local hit=0
    for x in "${STAGES[@]}"; do [ "$x" = "$from" ] && hit=1; [ "$x" = "$s" ] && break; done
    [ $hit = 1 ]; return
  fi
  [ ! -f "$OUT/.done-$s" ] || [ $dry = 1 ]
}

# run <stage> <cmd...>: print the exact command; run it unless --dry-run
run() {
  local s=$1; shift
  echo "  $(q "$@")"
  [ $dry = 1 ] && return 0
  "$@"
}

ensure_autoround() {
  local prefix marker
  if [ $dry = 1 ]; then
    if [ -d "$AR_SRC" ]; then
      echo "  # once: git -C $AR_SRC rev-parse HEAD == $AR_COMMIT, clean; then"
      echo "  $(q "$VENVPY" -m pip install --no-deps --no-build-isolation "$AR_SRC")"
    else
      echo "  # once: $(q "$VENVPY" -m pip install --no-deps "$AR_SRC")"
    fi
    echo "  # once: $(q "$VENVPY" -m pip install datasets py-cpuinfo pydantic accelerate)"
    return 0
  fi
  [ -x "$VENVPY" ] || { echo "VENVPY=$VENVPY is not an executable python" >&2; exit 2; }
  prefix=$("$VENVPY" -c 'import sys; print(sys.prefix)')
  marker="$prefix/.kolibri-autoround-commit"
  if [ "$(cat "$marker" 2>/dev/null || true)" != "$AR_COMMIT" ]; then
    if [ -d "$AR_SRC" ]; then
      local head
      head=$(git -C "$AR_SRC" rev-parse HEAD)
      [ "$head" = "$AR_COMMIT" ] || { echo "AR_SRC $AR_SRC is at $head, the recipe pins $AR_COMMIT" >&2; exit 2; }
      [ -z "$(git -C "$AR_SRC" status --porcelain --untracked-files=no)" ] ||
        { echo "AR_SRC $AR_SRC has local changes; the recipe needs $AR_COMMIT as committed" >&2; exit 2; }
      "$VENVPY" -m pip install -q --no-deps --no-build-isolation "$AR_SRC"
    else
      "$VENVPY" -m pip install -q --no-deps "$AR_SRC"
    fi
    "$VENVPY" -m pip install -q datasets py-cpuinfo pydantic accelerate
    echo "$AR_COMMIT" > "$marker"
  fi
  "$VENVPY" - <<'PY'
import auto_round
assert auto_round.__version__.startswith("0.17"), auto_round.__version__
print(f"auto-round {auto_round.__version__} from {auto_round.__file__}")
PY
}

stage() {
  local s=$1
  if ! selected "$s"; then
    if [ -f "$OUT/.done-$s" ]; then
      echo "== $s: done $(cat "$OUT/.done-$s"), skipped - --only $s / --from $s reruns it"
    else
      echo "== $s: not selected"
    fi
    return 1
  fi
  echo "== $s"
  return 0
}

done_stage() { [ $dry = 1 ] || { mkdir -p "$OUT"; date -u +%FT%TZ > "$OUT/.done-$1"; }; }

echo "quantize_kolibri1: MODEL=$MODEL OUT=$OUT DEVICE=$DEVICE NSAMPLES=$NSAMPLES ATTN=$ATTN ITERS=$ITERS" \
     "SEQLEN=$SEQLEN auto-round $AR_COMMIT$([ $dry = 1 ] && echo ' (dry run)')"
[ $dry = 1 ] || mkdir -p "$OUT"
export KOLIBRI_AR_COMMIT="$AR_COMMIT"
[ -d "$AR_SRC" ] && export KOLIBRI_AR_SRC_DIR="$AR_SRC"
cd "$ROOT"

if stage calib; then
  run calib "$GEN_PY" "$K/calib.py" --model "$MODEL" --shim "$SHIM" --out "$OUT" --nsamples "$NSAMPLES" \
    --seqlen "$SEQLEN" --eval-rows "$EVAL_ROWS" --backend "$GEN_BACKEND" --device "$DEVICE" --tp "$TP" \
    --gen-max "$GEN_MAX" --doc-gen-max "$DOC_GEN_MAX" --doc-tokens "$DOC_TOKENS"
  done_stage calib
fi

if stage coverage; then
  run coverage "$VENVPY" "$K/coverage.py" --model "$MODEL" --calib "$OUT/calib.safetensors" --out "$OUT" \
    --floor "$COVERAGE_FLOOR" --rounds "$COVERAGE_ROUNDS" --device "$DEVICE"
  done_stage coverage
fi

for s in rtn tune; do
  if stage $s; then
    ensure_autoround
    it=0; [ $s = tune ] && it=$ITERS
    for a in "${arms[@]}"; do
      run $s "$VENVPY" "$K/autoround_run.py" --model "$MODEL" --shim "$SHIM" --calib "$OUT/calib_final.safetensors" \
        --out "$OUT/$s-attn_$a" --iters "$it" --attn "$a" --device "$DEVICE" --seqlen "$SEQLEN" \
        --batch-size "$BATCH" --torch-compile "$COMPILE"
    done
    done_stage $s
  fi
done

arm_args=()
for s in rtn tune; do
  for a in "${arms[@]}"; do
    if [ $dry = 1 ] || [ -d "$OUT/$s-attn_$a" ]; then arm_args+=(--arm "$s-attn_$a=$OUT/$s-attn_$a"); fi
  done
done

if stage eval; then
  [ ${#arm_args[@]} -gt 0 ] || { echo "eval: no arm under $OUT (run rtn / tune first)" >&2; exit 2; }
  run eval "$VENVPY" "$K/evaluate.py" --model "$MODEL" --sets "$OUT" --out "$OUT/eval" --device "$DEVICE" "${arm_args[@]}"
  done_stage eval
fi

if stage check; then
  for s in rtn tune; do
    for a in "${arms[@]}"; do
      if [ $dry = 1 ] || [ -d "$OUT/$s-attn_$a" ]; then
        run check "$VENVPY" "$K/check.py" "$OUT/$s-attn_$a" --source "$MODEL" --attn "$a" --json "$OUT/check-$s-attn_$a.json"
      fi
    done
  done
  done_stage check
fi

if stage card; then
  run card "$VENVPY" "$K/card.py" --work "$OUT" --arm "$ARM"
  done_stage card
fi
echo "quantize_kolibri1: finished$([ $dry = 1 ] && echo ' (dry run: nothing was run)')"
